---
title: "derivations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{derivations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Inverse Distribution

If $X$ is a random variable with distribution function $F(x)$, then the inverse distribution is defined by the random variable $Y = 1 / X$. This distribution is defined whenever $P(X = 0) = 0$.

The CDF $F_Y(y)$ can be derived under two cases: either $y<0$ or $y>0$.

For $y<0$,
\begin{align}
P\left(\frac{1}{X} \leq y\right) &= P\left(X \geq \frac{1}{y} \cap X\leq0\right) \
&= F(0) - F\left(\frac{1}{y}\right) + P\left(X = \frac{1}{y}\right)
\end{align}

For $y>0$:
\begin{align}
P\left(\frac{1}{X} \leq y\right) &= P\left(X \geq \frac{1}{y} \cup X\leq0\right) \
&= 1 - P\left(X < \frac{1}{y} \cap X>0\right)
&= 1 + F(0) - F\left(\frac{1}{y}\right) + P\left(X = \frac{1}{y}\right)
\end{align}

Putting the two together,
$$F_Y(y) = I(y \geq 0) + F(0) - F\left(\frac{1}{y}\right) + P\left(X = \frac{1}{y}\right),$$
where $I$ is the indicator evaluating to 1 if its argument is true, and 0 otherwise. For $y = 0$, the function evaluates to $F(0)$ in the limit from both sides -- the same y-intercept as the original distribution's CDF. For evaluation in R, since $1/0$ evaluates to `Inf` as opposed to `-Inf`, it is convenient to include $y = 0$ in the indicator function to ensure proper evaluation at 0.

For the special case of continuous distributions having $X>0$ almost surely, or $X<0$ almost surely, the CDF reduces in both cases to
$$F_Y(y) = 1 - F\left(\frac{1}{y}\right).$$

To arrive at the quantile function, note that the term $P(X = 1/y)$ has the effect of switching $F$ from being right-continuous to left-continuous, and has no effect on the definition of quantile used in the probaverse that $Q_Y(p) = \inf\{y \in \mathbb{R}: F_Y(y) \leq p\}$. But for transparency, write $F^{\ell}(x) = F(x) - P(X = x)$ for $x\in\mathbb{R}$, the left-continuous CDF, to simplify the CDF to
$$F_Y(y) = I(y > 0) + F(0) - F^{\ell}\left(\frac{1}{y}\right).$$
To further simplify, the quantile function $Q_Y(p)$ can be derived for $p\in[0, F(0))$ separately from $p\in(F(0), 1]$, because they correspond to $y < 0$ and $y > 0$, respectively, so that the indicator function is constant in both cases. Doing so gives the final quantile function,
$$Q_Y(p) = \frac{1}{Q\left(F(0) + I(p > F(0)) -p\right)},$$
for $p \in [0, 1] \backslash \{F(0)\}$. For $p = F(0)$,
\begin{formula}
Q_Y(F(0)) = 
\begin{cases}
1 / x_{\ell}, & if x_{\ell} \in \mathbb{R}, \\
0, & if x_{\ell} = -\infty,
\end{cases}
\end{formula}
where $x_{\ell}$ is the left endpoint of the distribution $F$ (the infimum of the support of $F$). In R, the above formula evaluates properly if the convention $Q(0) = x_{\ell}$ is adopted as opposed to having $Q(0)$ strictly evaluate to $\-infty$, which is the case for the default `stats` package.
